stages:
  preprocess:
    cmd: python src/preprocess.py
    outs:
      - data/wine_train.csv
      - data/wine_test.csv
  train:
    cmd: python src/train.py
    deps:
      - data/wine_train.csv
    params:
      - train.test_size
      - train.random_state
      - train.model.max_iter
      - train.model.learning_rate
    outs:
      - model/model.pkl
