stages:
  preprocess:
    cmd: python src/preprocess.py
    outs:
      - data/wine_train.csv
      - data/wine_test.csv
  train:
    cmd: python src/train.py
    deps:
      - data/wine_train.csv
    outs:
      - model/model.pkl
